### ISSUE TITLE
Empty output file after generating iterative list

### ISSUE THREAD

**Issue by ghost** [3ndG4me/spraygen#6]
Hello, again.

Hope you're all well.

I managed to pick some parameters which don't generate an error. However, it doesn't generate any output, either.

Here's what I got...

```
$ >python3 spraygen.py --type iterative --mode plain --sort random --max_length=2 --iter=ascii -o "PasswordList_$(date +%y%m%d@%H%M%S).txt"

     _
    (  \_
    (    \_
    (       \_  
    (         \_            ___
    ( Password   \         |   |
    (   Spray     |คคคคคคคค|___|
    (           _ /          |
    (       _ /         /~~~~~~~~~\
    (   _ /            (  Spray    )
    (_/                 |  This   |
                        |         |
                        | Get     |
                        |  Creds  |
                        |_________|

    Original Art by Alex Chudnovsky (Unaffiliated)
    Spraygen tool by 3ndG4me
    Version 1.6
    
[*] Info: Year Start not provided, setting to current year...
[*] Info: Year End not provided, setting to current year...
[*] Info: Generating PLAIN list...
[*] Info: Generating ITERATIVE list...
[*] Info: List size will be: 4
[*] Info: List keyspace will be: ascii
[*] Info: This is generating literally every permutation in that keyspace, this will take some time...
[*] Info: Generating ascii keyspace list |################################| 100%
[+] Success: --- generated iterative in 66.94957995414734 seconds ---
[*] Info: Skipping separators and attributes...
[*] Info: Adding new generated items to the list...
[*] Info: Adding relevant attribute/separator permutations to final list, this could take some time...
[*] Info: Progress |################################| 100%
[+] Success: --- initial list built in 66.95010900497437 seconds ---
[+] Success: Bulding final list!
[+] Success: Writing output to: PasswordList_220327@225645.txt


[+] Success: --- finished in 66.95020365715027 seconds ---
[+] Success: Done!
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
XXXX@XXXX-PC1 - Sun Mar 27 22:57 - Load: 1.09 
~/.../spraygen-main $ >ll PasswordList_220327@225645.txt 
-rw-rw-r-- 1 XXXX XXXX 0 Mar 27 22:57 'PasswordList_220327@225645.txt'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
XXXX@XXXX-PC1 - Sun Mar 27 22:58 - Load: 1.09 
~/.../spraygen-main $ >cat PasswordList_220327@225645.txt 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
XXXX@XXXX-PC1 - Sun Mar 27 22:58 - Load: 1.09 
~/.../spraygen-main $ >

```
No write errors, no syntax or code errors this time, in fact no errors of any kind.  It spent over a minute bulding the list but didn't actually produce anything!

I **must** be missing something incredibly obvious, but I can't think what. Maybe I'm just tired and making oversight after oversight.

Thank you for any correction you can give me.

Best regards.

**Comment by 3ndG4me** [comment]
Hey! Apologies again for the delay.
 
Just tested this looks like you're simply using the wrong combo of args for iterative list. Iterative list need the `--size` argument to set the length of the the words in the list you wish to generate. Looks like you provided a `--max_length` of `2` when it should be a `--size=2`. In this example the iterative list defaulted to generating with a size of `4` but because your max_length was set to `2` the output was never added to the final generated list which is why it becomes empty.

This is just a set of incompatible arguments, all final list get put through the same filter, but there is no need to specify a min/max length with iterative builds since the size will be set if you use the `--size` parameter. All other options may build passwords that are longer, and as such, specifying the min/max length will filter out an outliers in the final list build. Simply swap `--max_length` for `--size` and you'll be golden!

`python3 spraygen.py --type iterative --mode plain --sort random --size=2 --iter=ascii -o "PasswordList_$(date +%y%m%d@%H%M%S).txt"`
